source:
  shopDomain: ""
  dbHost: ""
  dbPort: ""
  dbUser: ""
  dbPsw: ""
  sourceDbName: ""
  sshhost: ""
  sshpsw: ""
  sshport: "-p 22"
  saleschannelId: ""
  ignoreTableData: "--ignore-table=$sourceDB.cart --ignore-table=$sourceDB.customer_recovery --ignore-table=$sourceDB.dead_message --ignore-table=$sourceDB.enqueue"
  rsyncExcludeFiles: ""
target:
  targetShopDomain: "localhost"
  targetDbHost: "127.0.0.1"
  targetDbName: ""
  targetDbPort: "3306"
  targetDbUser: "root"
  targetDbPswd: "root"
  licenseHost: "localhost"
  targetUserPass: "shopware"